Update the REAME File
0xADE1A1DE/AssemblyLine pull request #16
Opened 2022-04-01 10:50 UTC by Neo-Outis

1. Update the correct procedure of installing the AssemblyLine
2. Update the Full Example, it is now an actual and working Full Example
3. Update an instruction of error shooting(ldconfig issue).

2022-04-04 23:05 UTC, dderjoel requested changes

2022-04-04 23:05 UTC, dderjoel commented on README.md
> +1. `$ bash autogen.sh` to generate the configure file
```suggestion
1. `$ bash autogen.sh` to generate the configure file (If cloned from repository. Can be skipped, when using the tarball)
```

2022-04-04 23:05 UTC, dderjoel commented on README.md
> +### ldconfig Issue
Lets put this into a separate file `TROUBLESHOOTING.md`.

2022-05-27 11:13 UTC, Neo-Outis commented
Done.

2022-05-30 03:50 UTC, dderjoel approved these changes

2022-05-30 03:51 UTC, merged